name: Run pytest 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
      - run: conda --version
      - run: which python
      - name: Install dependencies
        run: |
          conda install --file requirements.txt
          conda install -c omnia openmm  
          conda install pip 
          pip install -e . 
      - name: Test with pytest
        run: |          
          pytest
